config/routes.rb
Bridge::Application.routes.draw do

  root 'home#index'

  get 'travel' => 'home#travel'
  get 'comment' => 'home#comment'

  get 'question' => 'home#question'
  get 'customize' => 'home#customize'

  get 'place' => 'home#place'
  get 'theme' => 'home#theme'

  get 'edu' => 'educations#index'
  get 'jiangzuo' => 'educations#jiangzuo'
  get 'hezuo' => 'educations#hezuo'

  get 'download' => 'educations#download'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  def index
  end

  def hezuo
  end

  def jiangzuo

  end

  def download
    send_file params[:file]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def travel
  end

  def customize
  end

  def theme
    @themes = ["主题公园","传统观光","名校项目","特色项目","体育活动","海滩","博物馆科技馆"]
    @index = params[:id].to_i
    @images = ["themepark.png","tranditional.png","campus.png","tese.png","sports.png","beach.png","museum.png"]
  end

  def place
    @places = ["洛杉矶","橙县","圣地亚哥"]
    @index = params[:id].to_i
  end

  def comment
    @comment = [ "在来到美国之前，我就一直盼着这次夏令营了。感觉自己信心满满，毫无担心。报名时我
看到了营地，一点也没有辜负我的期待-这是一个超可爱的营地，环境自然，宿舍是很温
馨的小木屋，还有泳池和球场等等……这里的孩子都很友好，只要乐于与她们交流，即使
听不懂也没关系，她们完全不会介意……辅导员也很友好，她们会鼓励任何人去尝试新鲜
的事，不管做得好坏如何他们都会为你自豪……放心大胆的去玩吧，美国孩子会欢迎任何
国籍的营员……今天就要走了耶，好不舍！这里的所有人仿佛都在对我们微笑呢。还记得
我攀岩的时候，所有人都声嘶力竭地对我喊“You can do it!”“Come on!”然后我就突然爬到
顶了。一切的一切都好友爱。来之前，我都没想到自己临走时会如此不舍。哎，明年夏天
希望还能来吧。昨天晚上告别会上一明一灭的烛光，好像就是在倾诉呢。再见了，营地！",

"今天是我的生日哦！好兴奋好兴奋！今天，我们去了迪斯尼乐园。人好多哦，各种颜色
的人都有……我从工作人员地方得到了一枚生日纪念章，很可爱，很有纪念意义。一路
上，许多人对我祝福，可爽了，跟女王一样耶！每次对他们点头致谢，我总会感叹：美
国真友爱啊……今天一天都在赶往优胜美地的路上，不过我们看到了很多很值得一观的景
致……夜晚10:30左右我们到达了优胜美地的小木屋。由于是在黑暗中没有看到清楚的轮
廓，但应该很棒。室内很温馨，有些复古的味道，还有我梦想中的可爱小床和阳台上高端
大气上档次的沐光（沐浴阳光）桌（我自己编的）。一切都有憨厚笨拙的大黑熊做装饰，
看起来好可爱！唯一恐怖的是晚上可能会有熊光临，但我觉得很好玩。合上百叶窗，今天
结束了，好期待明天的游玩……今天是小木屋新的一天。早上，我们在阳台的小桌上享用
了早餐，感觉好棒，鸟儿都叫的很婉转呢！晚上，我们四个小屁孩在阳台上吃了一顿地道
的中餐。好亲切的味道，我们都吃得嘴角流油，从没有那么畅快！晚上，爸妈都去阳台微
信了，我和屁孩们在楼下打台球，刚开始用的很别扭，通过老爸一番指教就顺畅很多。好
快乐！……今早匆匆忙忙出发赶路。要离开了，对我最爱的小木屋做些补充吧。来的那一
天我真的好兴奋，能住在那么浪漫的小木屋里！屋里的布置也很别出心裁，好多小家具都
有憨厚的大黑熊做装饰。房东一定是一个心思细腻的人吧。楼上的儿童卧室空间利用的很
棒，还有小床可以从床下拉出来呢！我同样很喜欢房子的外形。乳白色墙，有几个别致的小窗，第三层的小屋顶显得很活泼。Daizy真有眼光呐！",

"我们的蜜月旅行第二站前往南加州，经过朋友推荐选择了Daizy的茵莱桥私人定制旅游。
第一站在北加州是参加的旅行社的大团游，老公对每天在路上疲于奔命，吃不好睡不香意
见很大。茵莱桥贴心、轻松和灵活的行程安排让我们一下子找到了旅行的感觉。中午带我
们去吃的海景餐厅价钱太实惠了啊，彻底颠覆了我对美国餐饮又贵又没味的印象！最大的
惊喜是浪漫的科罗拉多大酒店，我们居然能像身边那些金发碧眼的当地人一样悠闲地坐在
露天海景咖啡厅，来上一杯鸡尾酒，面对着美不胜收的海边日落，彼此会心的一笑。美国
好玩的太多了，下次我们还会回来的，还要找Daizy和她的茵莱桥",

"我和女同伴从加拿大来美国看望侄女顺便旅游。侄女一家平时要工作太忙没有时间陪我
们，我们两个老太太虽然略通英文同伴也会开车，可是人生地不熟还是不敢冒险。侄女听
说了茵莱桥的私人定制服务就帮我们联系了。Daizy小姐花费了不少时间跟我们详细了解
需求和沟通行程安排，一路上更是体贴细心，担心我们沟通不便专程免费陪我们在奥特莱
斯购物了一天，帮我们取得奥莱的折扣券，还跟服务员讨价还价争取到额外折扣。这么周
到耐心细致的服务，实在很难得。我回去之后立刻向身边的朋友推荐了他们的服务。",

"我和先生第一次带两个年幼的儿子（一个5岁，一个2岁）来美国旅游，对于美国的具体
情况不太清楚，心里很没底。朋友是茵莱桥的老客户，因此向我们推荐了他们的服务。黄
小姐对我的问题和要求都是很快回复，行程根据我们的要求也是一再修改，全程一直很耐
心。我们考虑到孩子还小，9天的行程最后只准备玩迪斯尼、环球影城和乐高公园三个地
方，而且是全程自驾游。黄小姐不但为我们订好了商务舱的机票和卡宴SUV供出行，租好
了孩子的汽车座椅，还考虑到我们语言交流有困难贴心的为我们安排好车行的人到机场出
站口迎接我们去取车。因为加拿大的租车保险政策跟美国不同，黄小姐为了避免我们不花
冤枉的租车保险费，多次与车行和我们的保险公司咨询和协调保险方案，最终为我们找到
了一个最为经济的保险费方案。我们对茵莱桥的服务很满意，下次来美国还会选择他们！",

"今年夏天我们经过朋友的介绍体验了茵莱桥的私人定制家庭游。我们是两个家庭，我和我哥哥一家，
一共4个大人，4个孩子。茵莱桥的服务很周到，对于我们来之前的诸多问题和要求一一答复和满足，
甚至在即将启程的前三天对于我们行程上的临时变更都尽力想办法实现。由于要取消原定行程中已预
订的酒店和门票而改订别的城市的酒店，我本来以为会要交数目不菲的差额款，没想到茵莱桥仅仅收
取了很低的差价费，这跟我以前接触的其他旅行社借机坐地起价的做法很不一样，让我在出行之前就
对他们的诚信刮目相看。抵达美国之后，他们的服务果然没有令我们失望。孩子们参加夏令营非常开
心，这多亏了茵莱桥对夏令营营地细致的调查和给孩子们行前认真的培训，准备工作做得很到位，孩
子们心里有底，到了营地心态很放松。Daizy全程一直关注孩子在营地的情况，每天都会把营地的照
片发给我们家长看。后来我才知道，她还专程跟营地的营养师介绍了孩子们的饮食习惯并研究制定了
应急方案，以防孩子在营地饮食不习惯而影响身体健康。除了夏令营，在家庭旅游的这一部分茵莱桥
的行程设计也很新颖独特。让我们印象最深刻的当属圣地亚哥的直升飞机海岸线巡游、拉荷亚海滩的
皮划艇以及优胜美地的度假小木屋。这些在其他旅行社的行程安排中我从来没有见过。本来我们还有
点忐忑，没想到试过之后这么好玩，下次有朋友再来一定要告诉他们不能错过！总之，茵莱桥和
Daizy的服务我们非常满意，跟他们旅行将会颠覆你对旅行社的成见！现在，我们头疼的是，有了这
次经历，将来去别的地方旅行要求提高了很多啊！：）"
  ]
    @from = ["------------摘自12岁宁波女孩昀的夏令营营地日记","---------------摘自12岁宁波女孩昀的夏令营营地日记","------------来自北京的Amy浪漫双人定制游"," --------来自加拿大的Susan双人友情定制游"," --------来自加拿大的Angela家庭私人定制游","--------来自宁波的Chessy的家庭私人定制游"]
    @id = params[:id].to_i
  end

  def question
    @answers = ["当然可以。以两周的游学团为例：第一周家长和孩子
一起游玩；第二周则分头行动，孩子参加夏令营，家长独
享悠闲假期。除了国人热衷的经典旅游景点如赌城拉斯维
加斯、迪斯尼乐园、加州冒险乐园、洛杉矶环球影视城、
圣地亚哥海洋世界，还可以从我们为您精选的几十种美国
本地游客热衷的活动中选择您最感兴趣的项目，比如在南
加州几个著名的海滩度假胜地如圣塔芭芭拉、圣塔莫妮卡
、圣地亚哥体验各种水上娱乐项目，深入了解华人移民热
点洛杉矶市及橙县周边的多彩生活并安排权威专业人士直
接解答您关于孩子入学、投资房产、办理移民等等的问题
，亲临现场体验美国各大体育赛事如NBA、美国职业棒球
赛、职业橄榄球赛和职业足球俱乐部联赛，加州一号公路
及沿线小镇深度游，美国名校校区参观，夜游圣地亚哥市
中心酒吧一条街，奥特莱斯及当地折扣商场和会员超市购物等等。",

"我公司目前在推广业务期间，折扣力度很大，比市面
上的同类型私家团报价便宜20%以上。具体报价要根据您
的参团人数和行程而定，两人便可成团，人数越多，人均
价格越低。",

"价格包括在美期间除了餐饮外的所有费用，如酒店、
夏令营费用、各种门票、交通费、服务费等。我们的报价
不包括餐饮是因为我们希望不同口味偏好的客户能最大限
度地自由享用来自世界各地的著名美食。如客户希望我们
提供餐饮可以在定团时说明，我们很乐意为您提供，报价
将略为上升。司机和导游的服务费与小费也已计入报价，
您无需另付。我们会在您抵美后免费为您提供美国电话卡
，以方便您在美期间的生活。此外，我们还会在您赴美前
或抵美后的头两天对您和家人提供免费培训，内容包括日
常美语、风土人情、西方生活礼仪、夏令营内容和注意事
项等，让您的美国之行更加圆满顺利。另外，如果您需要
我们提供签证服务和代订机票服务，我们也可以满足您的
要求。",

"当然可以。如果您选择不参加夏令营，我们会为您制
订适合您家庭的旅游路线和行程安排。具体细节我们会在
您赴美之前与您确认。",

"在不改变已提前预定的酒店的前提下是可以的。不论
任何原因，如果您希望调整预先设定的行程，我们会最大
限度地尽力满足您的需求。",

"因为中美两国商品的差价较大，很多国内的朋友都喜
欢在回国前血拼一番，争取把机票钱赚回来！因此，在我
们的行程策划中，将会根据您的消费档次和需求为您诚挚
推荐不同的购物场所，包括奥特莱斯、大型购物商场、名
品折扣店、名牌精品店，以及需要会员卡只有本地人才能
光顾的量贩超市。如果您想体会当地人的生活和物价水平
，我们还可以安排您到美国连锁超市和本地华人超市购买
食物和生活用品，或者到农夫市场和小商品市场淘宝。我
们保证满足您的购物需求，让您满载而归！如果您不需要
安排购物，也可在确定行程时跟我们说明即可。",

"我们在帮助您和孩子选择夏令营的时候，会根据孩子
的年龄、个性、兴趣爱好以及英语水平选择最适合您孩子
的营地。有了我们的精心挑选和对您孩子的事先培训，孩
子们一定能尽情地体验和享受夏令营的每一天。我们还可
以根据需要安排您和（或）孩子入住当地美国白人家庭，
真实体会原汁原味的美国家庭日常生活方式。"
]
  @id = params[:id].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/educations/_leftnav.html.erb
<div class="bnavbar-left-edu">
    <div class="btn-group-vertical bbtn-group-edu" role="group">
      <button type="button" class="btn btn-default bbtn">
        <a href="#edugongsijianjie">公司简介</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#eduguanyuwomen">教育团队</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#eduyouxuexialingying">游学夏(冬)令营</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#eduliuxuejisu">留学寄宿</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#edujiaoyuwenhuajiaoliu">教育文化交流</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#edulianxiwomen">联系我们</a>
      </button>
    
  </div>
</div>

app/views/home/_block.html.erb
<div class="bblock" id="<%= block_id %>">
  <div style="background-image: url(<%= asset_path imgName %>)" class="full-img">
    <div class="panel panel-default bpanel">
      <div class="panel-body bpanel-body">
        <%= text %>
      </div>
    </div>
  </div>
</div>

app/views/home/_leftnav.html.erb
<div class="bnavbar-left">
  <div class="binner-control">
    <div class="btn-group-vertical bbtn-group" role="group">
      <button type="button" class="btn btn-default bbtn">
        <a href="#gongsijianjie">公司简介</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#lvyoutuandui">旅游团队</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#dingzhilvyou">定制旅游</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#kehupinglun">客户评价</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#changjianwenti">常见问题</a>
      </button>
      <button type="button" class="btn btn-default bbtn">
        <a href="#lianxifangshi">联系我们</a>
      </button>
    </div>
  </div>
</div>

app/views/home/_rightnavhorizontal.html.erb
<div class="btn-group bbutton" role="group" style="float: right; padding: 30px;">
  <p style="font-size: 20px;">搜索您感兴趣的旅游景点</p>
 <div class="btn-group" style="display: block">
    <button type="button" class="btn btn-default dropdown-toggle bbutton" data-toggle="dropdown" aria-expanded="false">
      选择主题 <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "主题公园", theme_path(:id=>0)%>
      </li>
      <li><%= link_to "传统观光", theme_path(:id=>1)%></li>
      <li><%= link_to "名校项目", theme_path(:id=>2)%></li>
      <li><%= link_to "特色项目", theme_path(:id=>3)%></li>
      <li><%= link_to "体育活动", theme_path(:id=>4)%></li>
      <li><%= link_to "海滩", theme_path(:id=>5)%></li>
      <li><%= link_to "博物馆科技馆", theme_path(:id=>6)%></li>
    </ul>
  </div>
 
  <div class="btn-group" style="display: block; margin-left: 10px;">
    <button type="button" class="btn btn-default dropdown-toggle bbutton" data-toggle="dropdown" aria-expanded="false">
      选择地区 <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "洛杉矶", place_path(:id=>0)%>
      </li>
      <li>
        <%= link_to "橙县", place_path(:id=>1)%>
      </li>
      <li><%= link_to "圣地亚哥", place_path(:id=>2)%></li>
    </ul>
  </div>
</div>

app/views/home/_rightnavvertical.html.erb
<div class="xuanzelvyou">
  <div class="btn-group" role="group">
  <p style="font-size: 20px;">搜索您感兴趣的<br>旅游景点</p>
   <div class="btn-group" style="float: none;">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        选择主题 <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "主题公园", theme_path(:id=>0)%>
        </li>
        <li><%= link_to "传统观光", theme_path(:id=>1)%></li>
        <li><%= link_to "名校项目", theme_path(:id=>2)%></li>
        <li><%= link_to "特色项目", theme_path(:id=>3)%></li>
        <li><%= link_to "体育活动", theme_path(:id=>4)%></li>
        <li><%= link_to "海滩", theme_path(:id=>5)%></li>
        <li><%= link_to "博物馆科技馆", theme_path(:id=>6)%></li>
      </ul>
    </div>
    <br>
    <p>OR</p>
    <div class="btn-group" style="float: none;">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        选择地区 <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "洛杉矶", place_path(:id=>0)%>
      </li>
      <li>
        <%= link_to "橙县", place_path(:id=>1)%>
      </li>
      <li><%= link_to "圣地亚哥", place_path(:id=>2)%></li>
    </ul>
    </div>
  </div>
</div>

app/views/home/comment.html.erb
<div class="col-sm-6 col-sm-offset-3" style="padding: 50px;">
  <h3><%= @comment[@id]%></h3>
  <p style="float:right;"><%= @from[@id]%></p>
</div>

app/views/home/index.html.erb
<div class="bblock" style="height:100%;">
  <div style="background-image: url(<%= asset_path 'bg.png' %>)" class="full-img">
    <div>
      <div class="col-sm-12" style="text-align: center;">
        <%= image_tag "logo.png", size: '300x270'%>
      </div>
      <div class="col-sm-8 col-sm-offset-2" style="text-align: center; color: white;">
        <h2>茵莱桥文化服务有限责任公司</h2>
        <h4 style="line-height: 1.5em;">  位于美国加州著名海滨度假胜地圣地亚哥市。我公司旨在促进中美两国日益频繁和深入的教育和文化交流，目前承接私人订制旅游、游学留学教育、商务考察访问、医疗就诊接诊等多项业务</h4>
      </div>
      <div class="col-sm-6">
        <div class="item-container">
          <%= link_to travel_path do%>
            <div>
              <%= image_tag "travellogo.png", size: '150x150', :class=>'image-item'%> <h3 class="sm-title">旅游</h3>
              <h3 class="h3-show">旅游</h3>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="item-container">
          <%= link_to edu_path do%>
            <div>
              <%= image_tag "edulogo.png", size: '150x150', :class=>'image-item'%> <h3 class="sm-title">教育</h3>
              <h3 class="h3-show">教育</h3>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/question.html.erb
<div class="col-sm-6 col-sm-offset-3" style="padding: 50px;">
  <h3><%= @answers[@id]%></h3>
</div>

app/views/home/travel.html.erb
<%= render 'shared/header', :imgName => 'header.png'%>
<%= render 'leftnav'%>
<%= render 'rightnavvertical'%>
<!-- <div class="bfloat">
  <%= image_tag "xialingying.png", :class=>'img-rounded'%>
</div>
 -->


<div class="bblock" id="gongsijianjie">
  <div style="background-image: url(<%= asset_path 'gongsijianjie.png' %>)" class="full-img">
    <div class="panel panel-default bpanel">
      <div class="panel-body bpanel-body">
        <p>茵莱桥文化服务有限责任公司（Enlite Bridge, LLC）位于美国加州著名海滨度假胜地圣地亚哥市。我公司旨在促进中美两国日益频繁和深入的教育和文化交流，目前承接<span style="font-size: 30px; font-style: italic; color: #2E99D0; font-weight: bold;">私人订制旅游、游学留学教育、商务考察访问、医疗就诊接诊</span>等多项业务.</p>
      </div>
    </div>
  </div>
</div>

<div class="bblock" id="lvyoutuandui" style="height: 1000px;">
  <div style="background-image: url(<%= asset_path 'lvyoutuandui.png' %>)" class="full-img">
    <div class="panel panel-default bpanel">
      <div class="panel-body bpanel-body">
        <div style="text-align: left">
          <%= image_tag "huangyi.png", :style=>'float: left; margin-right: 10px; width: 200px;'%>
          <p style="font-size: 18px;">黄怡 | 总裁</p>
          <p style="font-size: 18px;">Daizy Huang | CEO/Founder</p>
          <p style="font-size: 18px;">美国加州茵莱桥文化服务有限公司总裁。北京交通大学毕业并留校任教，后赴美定居十余年，拥有美国加州州立大学会计学硕士学位，曾任全球第5大会计师事务所BDO资深审计师，现为美国执业注册会计师。黄女士育有两子，现与任职资深高级软件工程师的先生定居于美国加利福利亚州著名的海滨度假胜地圣地亚哥市.</p>
        </div>
        <br>
        <br>
        <div style="text-align: right">
          <%= image_tag "liuyang.png", :style=>'float: right; margin-left: 10px;'%>
          <p style="font-size: 18px;">刘阳 | 北美大区商务与医疗旅行部指定顾问</p>
          <p style="font-size: 18px;">Yang Liu | Costomize Service Advisor</p>
          <p style="font-size: 18px;">茵莱桥文化服务有限公司北美地区商务与医疗旅行部业务负责人。北京交通大学及俄亥俄州立大学毕业。十分熟悉并了解美国工业制造业展会相关信息和北美各大医院的学术专业方向，就诊流程以及国际接诊情况，熟知美国中东部景点，购物商圈，人文历史以各地及游览攻略，擅长整合优化旅游行程，按照客人需求平衡时间-路线-价格，致力于打造适应顾客个性化需求的文化服务新体系.</p>
        </div>
    </div>
  </div>
</div>

<div class="bblock" id="dingzhilvyou">
  <div style="background-image: url(<%= asset_path 'dingzhilvyou.png' %>)" class="full-img">
    <div class="panel panel-default bpanel">
      <div class="panel-body bpanel-body">
        <p>本公司经营私人定制旅游的四项原则是“灵活、周到、流畅、专业”。大家印象中的组团旅游一定是行程古板，早出晚归，大部分时间花在路上行车，而客人只能选择既定路线，不能灵活调整。所以在我们的私人定制中，希望能颠覆这种不够人性化的组团模式，给客人有更好的旅游体验。我们会在行程前耐心了解客户需求，协助客人自主确定行程，旅程中也可以随时调整行程，并能为后续的一系列衍生需求提供完善专业的服务。
          <span>
            <%= link_to "了解更多信息", customize_path, :class=>'liaojiegengduo'%>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="bblock" id="kehupinglun">
  <div style="background-image: url(<%= asset_path 'kehupinglun.png' %>)" class="full-img">
    <div class="panel panel-default bpanel">
      <div class="panel-body bpanel-body">
        <%= link_to comment_path(:id=>0) do%>
          <p>1.来之前，我都没想到自己临走时会如此不舍。哎，明年夏天希望还能来吧...</p>
        <% end %>
        <%= link_to comment_path(:id=>1) do%>
          <p>2.一路上，许多人对我祝福...每次对他们点头致谢，我总会感叹：美国真友爱啊!…</p>
        <% end %>
        <%= link_to comment_path(:id=>2) do%>
          <p>3.茵莱桥贴心、轻松和灵活的行程安排让我们一下子找到了旅行的感觉...</p>
        <% end %>
        <%= link_to comment_path(:id=>3) do%>
          <p>4.Daizy小姐花费了不少时间跟我们详细了解需求和沟通行程安排，一路上更是体贴细心...</p>
        <% end %>
        <%= link_to comment_path(:id=>4) do%>
          <p>5.我们对茵莱桥的服务很满意，下次来美国还会选择他们！...</p>
        <% end %>
        <%= link_to comment_path(:id=>5) do%>
          <p>6.茵莱桥的服务很周到，对于我们来之前的诸多问题和要求一一答复和满足...</p>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="bblock" id="changjianwenti">
  <div style="background-image: url(<%= asset_path 'changjianwenti.png' %>)" class="full-img">
    <div class="panel panel-default bpanel">
      <div class="panel-body bpanel-body">
        <%= link_to question_path(:id=>0) do%>
          <p> 1. 我们对美国不太了解，您能提供一份大致的行程安排吗？</p>
        <% end %>
        <%= link_to question_path(:id=>1) do%>
          <p> 2. 您的价位是多少?</p>
        <% end %>
        <%= link_to question_path(:id=>2) do%>
          <p> 3. 这个价格具体包含了什么?</p>
        <% end %>
        <%= link_to question_path(:id=>3) do%>
          <p> 4. 我们孩子还小，可以选择不参加夏令营吗？</p>
        <% end %>
        <%= link_to question_path(:id=>4) do%>
          <p> 5. 如果我们抵美之后希望改变行程，这样可行吗？</p>
        <% end %>
        <%= link_to question_path(:id=>5) do%>
          <p> 6. 我们对购物很有兴趣，您行程策划中对购物有很多安排吗？</p>
        <% end %>
        <%= link_to question_path(:id=>6) do%>
          <p> 7. 孩子参加全英文的夏令营能听懂吗？</p>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="bup" style="text-align: center;">
  <span class="glyphicon glyphicon glyphicon-chevron-up" style="color:#34A1C4; "aria-hidden="true"></span>
  <p style="color: #34A1C4;">返回顶部</p>
</div>

<%= render 'shared/footer', :imgName => 'lianxifangshi.png' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bridge</title>
  <meta name="viewport" content="width=1000, height=500, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/shared/_nav.html.erb
<div style="width=100%;">
  <%= image_tag "blankheader.png", :style=>'width:100%;'%>
</div>

<div style="padding: 0px 100px;">
  <button type="button" class="btn btn-default bbutton">
    <%= link_to "返回", travel_path %>
  </button>
  <%= render 'rightnavhorizontal'%>
</div>